function y = check_equality_constraints(network, vars, lin_pipes, sim_input)
    % Calculate network equality constraints
    [Aeq_ht, beq_ht] = ht_constraints(vars, network);
    [Aeq_nodeq, beq_nodeq] = nodeq_constraints(vars, network, sim_input);
    [Aeq_pumpgroup, beq_pumpgroup] = pumpgroup_constraints(vars, network);
    [Aeq_dhpipe, beq_dhpipe] = pipe_headloss_constraints(...
        vars, network, sim_input, lin_pipes);
    % Calculate equality constraints related to linearization
    [Aeq_qpipe, beq_qpipe] = ww_constraints(vars, network);
    [Aeq_bb, beq_bb] = bb_constraints(vars);
    [Aeq_ss, beq_ss] = ss_constraints(vars);
    [Aeq_qq, beq_qq] = qq_constraints(vars);
    [Aeq_aa, beq_aa] = aa_constraints(vars);
    % Create reports
    eq_ineq_constraint_report(...
        "Tank head equality constraints", ...
        "reports/equality/ht_constraints.report", ...
        Aeq_ht, beq_ht, vars);
    eq_ineq_constraint_report(...
        "Flow continuity constraints", ...
        "reports/equality/nodeq_constraints.report", ...
        Aeq_nodeq, beq_nodeq, vars);
    eq_ineq_constraint_report(...
        "Pump group flow equality constraints",...
        "reports/equality/pumpgroup_constraints.report",...
        Aeq_pumpgroup, beq_pumpgroup, vars);
    eq_ineq_constraint_report(...
        "Pipe headloss equality constraints",...
        "reports/equality/dhpipe_constraints.report",...
        Aeq_dhpipe, beq_dhpipe, vars);
    eq_ineq_constraint_report(...
        "Pipe segment flow equality constraints",...
        "reports/equality/qpipe_constraints.report",...
        Aeq_qpipe, beq_qpipe, vars);
    eq_ineq_constraint_report(...
        "Pipe segment selection equality constraints",...
        "reports/equality/bb_constraints.report",...
        Aeq_bb, beq_bb, vars);
    eq_ineq_constraint_report(...
        "Pump segment speed equality constraints",...
        "reports/equality/ss_constraints.report",...
        Aeq_ss, beq_ss, vars);
    eq_ineq_constraint_report(...
        "Pump segment flow equality constraints",...
        "reports/equality/qq_constraints.report",...
        Aeq_qq, beq_qq, vars);
    eq_ineq_constraint_report(...
        "Pump segment selection equality constraints",...
        "reports/equality/aa_constraints.report",...
        Aeq_aa, beq_aa, vars);
end
