tests = {'test_intcon_vector_creation.m', 'test_power_linearization.m', ...
  'test_A_b_creation.m', 'test_obj_vector_creation.m', ...
  'test_pump_linearization.m', 'test_Aeq_beq_creation.m', ...
  'test_pipe_linearization.m'};
for test_index = 1:numel(tests)
  run(tests{test_index})
end
